CREATE DATABASE IF NOT EXISTS `cache_test`;
USE `cache_test`;
CREATE TABLE cache (
    `cid` VARCHAR(255) NOT NULL,
    `chunk` VARCHAR(255) NOT NULL,
    `ttl` DATETIME,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`cid`),
    UNIQUE (`cid`)
);
